#!/usr/bin/env bash
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || { echo "install_hooks: not in a git repository" >&2; exit 1; }
SRC="$ROOT/scripts/pre_push_scan.sh"; [ -f "$SRC" ] || { echo "install_hooks: $SRC missing" >&2; exit 1; }
HOOK_DIR="$(git -C "$ROOT" rev-parse --path-format=absolute --git-path hooks 2>/dev/null || true)"
if [ -z "$HOOK_DIR" ]; then
  HOOK_DIR="$(git -C "$ROOT" rev-parse --git-path hooks)"; case "$HOOK_DIR" in /*) :;; *) HOOK_DIR="$ROOT/$HOOK_DIR";; esac
fi
DST="$HOOK_DIR/pre-push"; mkdir -p "$HOOK_DIR"
if [ -e "$DST" ] && ! grep -q 'Agentic SSD governance dispatcher' "$DST" 2>/dev/null; then
  echo "install_hooks: existing pre-push hook at $DST is not governance-managed; refusing to overwrite it." >&2
  echo "Merge the existing behavior into a hook manager or record an approved migration." >&2
  exit 1
fi
cat > "$DST" <<'HOOK'
#!/usr/bin/env bash
# Agentic SSD governance dispatcher — generated by scripts/install_hooks.sh.
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || { echo "BLOCKED: cannot resolve repository root" >&2; exit 1; }
exec bash "$ROOT/scripts/pre_push_scan.sh" "$@"
HOOK
chmod +x "$DST"
echo "install_hooks: pre-push hook installed at $DST"
