#!/usr/bin/env bash
# Installs the governance pre-push dispatcher.
#
# The scan script's location is resolved dynamically rather than hard-coded:
# the repository layout moved from a top-level `scripts/` directory to
# per-stack `harness/<stack>/scripts/` plus the shared kernel in
# `harness/shared/`. Older checkouts still use `scripts/`, so all known
# locations are probed and the first hit wins (backwards compatible).
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || { echo "install_hooks: not in a git repository" >&2; exit 1; }

SCAN_BASENAME="pre_push_scan.sh"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Candidate locations, most specific first. A sibling of this script wins so a
# per-stack copy stays self-consistent; then the shared kernel; then the
# legacy top-level layout.
CANDIDATES=(
  "$SCRIPT_DIR/$SCAN_BASENAME"
  "$ROOT/harness/shared/$SCAN_BASENAME"
  "$ROOT/scripts/$SCAN_BASENAME"
)

SRC=""
for candidate in "${CANDIDATES[@]}"; do
  if [ -f "$candidate" ]; then SRC="$candidate"; break; fi
done

if [ -z "$SRC" ]; then
  echo "install_hooks: could not locate $SCAN_BASENAME in any known location:" >&2
  for candidate in "${CANDIDATES[@]}"; do echo "  - $candidate" >&2; done
  exit 1
fi

# Store the scan path relative to the repository root so the generated hook
# keeps working if the clone is moved or renamed.
SRC_REL="${SRC#"$ROOT"/}"

HOOK_DIR="$(git -C "$ROOT" rev-parse --path-format=absolute --git-path hooks 2>/dev/null || true)"
if [ -z "$HOOK_DIR" ]; then
  HOOK_DIR="$(git -C "$ROOT" rev-parse --git-path hooks)"; case "$HOOK_DIR" in /*) :;; *) HOOK_DIR="$ROOT/$HOOK_DIR";; esac
fi
DST="$HOOK_DIR/pre-push"; mkdir -p "$HOOK_DIR"
if [ -e "$DST" ] && ! grep -q 'Agentic SSD governance dispatcher' "$DST" 2>/dev/null; then
  echo "install_hooks: existing pre-push hook at $DST is not governance-managed; refusing to overwrite it." >&2
  echo "Merge the existing behavior into a hook manager or record an approved migration." >&2
  exit 1
fi
cat > "$DST" <<HOOK
#!/usr/bin/env bash
# Agentic SSD governance dispatcher — generated by install_hooks.sh.
# The scan path below was resolved at install time; do not hard-code it.
set -euo pipefail
ROOT="\$(git rev-parse --show-toplevel 2>/dev/null)" || { echo "BLOCKED: cannot resolve repository root" >&2; exit 1; }
SCAN="\$ROOT/$SRC_REL"
[ -f "\$SCAN" ] || { echo "BLOCKED: governance scan missing at \$SCAN; re-run install_hooks.sh" >&2; exit 1; }
exec bash "\$SCAN" "\$@"
HOOK
chmod +x "$DST"
echo "install_hooks: pre-push hook installed at $DST (scan: $SRC_REL)"
