name: CI
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.11"
      - name: Install Node dependencies
        run: |
          cd harness/node
          npm install -g pnpm
          pnpm install
      - name: Install Python dependencies
        run: pip install -r requirements-dev.txt
      - name: Run CI
        run: make ci
